# Generated by Django 5.1.6 on 2025-02-11 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maceio_in', '0002_department_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='description',
            field=models.TextField(blank=True, default='Sem Descrição', null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='description',
            field=models.TextField(blank=True, default='Sem Descrição', null=True),
        ),
    ]
